package it.uniroma3.siw.easyCrag.model;

public enum RegioneEnum {
	ABRUZZO, BASILICATA, CALABRIA, EMILIA_ROMAGNA, FRIULI_VENEZIA_GIULIA, LAZIO, LIGUARIA, LOMBARDIA, MARCHE, MOLISE, PIEMONTE, PUGLIA, 
	SARDEGNA, SICILIA, TOSCANA, TRENTINO_ALTO_ADIGE, UMBRIA, VALLE_DA_AOSTA, VENETO;
	
	private String nome;
	
	
}
